[module]
name = "Landing Zone Module"
url = "https://github.com/rescile/landing-zone-module"
version = "0.0.1"
description = "The AWS provider module adds the configuration schemas and properties required by a landing zone blueprint to interact with and manage AWS infrastructure APIs."
rescile_version = ">=0.1.201"

[params.solution]
description = "A freeform name describing the service that is deployed, this entry is used for naming conventions."
required = true
default = "Solution"

# Temp entry for offline development
[params.tenant]
description = "The tenant represents the organization that owns a service."
required = true
default = "Rescile"
