origin_resource = "endpoint"

provider_name = { "function!" = "{{- origin_resource.name | regexp(expr='s/^([^-]+)-.*/\\1/') | lower -}}" }
provider = { "json!" = "{{- provider_name -}}.json" }
services = { "json!" = "{{- provider_name -}}.json", jmespath = "values(roles)[?service == 'compute' ] | [0]" }

[[create_resource]]
match_on = [{ property = "function", value = "compute" }]
resource_type = "{{- origin_resource.function | lower -}}"
relation_type = "DEFINED_BY"
name = "{{- origin_resource.name | regexp(expr='s/^([^-]+-[^-]+-[^-]+)-.*/\\1/') | lower -}}"
[create_resource.properties]
function = "{{- params.solution -}}"
provider = "{{- provider_name -}}"
component = "{{- services.component -}}"
description = "Compute infrastructure provided by {{ provider.display }} is an on-demand, scalable processing power—ranging from virtual machines to serverless containers—that is managed entirely through code. Access and inter-node communication rely on dynamic, short-lived IAM tokens and automated TLS certificates rather than static passwords."
created = "{{- now(utc=true) | date(format='%Y-%m-%dT%H:%M:%SZ') -}}"

origin_resource = "compute"

decoder = {
    "ec2" = "instance",
    "autoscaling" = "fleet",
    "ec2instanceconnect" = "access",
    "imagebuilder" = "pipeline"
}

[[create_resource]]
create_from = { property = "component" }
relation_type = "DERIVED_FROM"
name = "{{- origin_resource.name | regexp(expr='s/^([^-]+-[^-]+)-.*/\\1/') | lower -}}-{{- origin_resource._type -}}-{{- decoder[property.value] | lower -}}"
[create_resource.properties]
function = "{{- property.value -}}"
created = "{{- now(utc=true) | date(format='%Y-%m-%dT%H:%M:%SZ') -}}"
