origin_resource = "network"

provider_name = { "function!" = "{{- origin_resource.name | regexp(expr='s/^([^-]+)-.*/\\1/') | lower -}}" }
provider = { "json!" = "{{- provider_name -}}.json" }
subnets = { "template!" = '''
{%- set count = origin_resource.subnet | length -%}
{%- set range = origin_resource.cidr -%}
{{- range | cidr_split_n(n=count) | join(sep=',') -}}
''' }

[[create_resource]]
create_from = { property = "subnet" }
relation_type = "DERIVED_FROM"
name = "{{ origin_resource.name | regexp(expr='s/^([^-]+-[^-]+-[^-]+)-.*/\\1/') | lower }}-{{- provider.dictionary.subnet -}}_{{- property.value -}}"
[create_resource.properties]
function = "{{- origin_resource.function -}}"
cidr = "{{- subnets[property.index] -}}"
description = "tbd"
created = "{{- now(utc=true) | date(format='%Y-%m-%dT%H:%M:%SZ') -}}"
