origin_resource = "resolver"

provider_name = { "function!" = "{{- origin_resource.name | regexp(expr='s/^([^-]+)-.*/\\1/') | lower -}}" }
provider = { "json!" = "{{- provider_name -}}.json" }

[[create_resource]]
create_from = { property = "zone" }
relation_type = "DEPENDS_ON"
name = "{{ origin_resource.name | regexp(expr='s/^([^-]+)-.*/\\1/') | lower }}-{{- origin_resource.function -}}-{{- provider.dictionary.zone -}}"
[create_resource.properties]
function = "{{- origin_resource.function -}}"
domain = "{{- property.value | lower -}}"
description = "The {{ origin_resource.function }} hosted DNS zone is an administrative namespace that a single entity manages, containing resource records that map domain names to IP addresses."
created = "{{- now(utc=true) | date(format='%Y-%m-%dT%H:%M:%SZ') -}}"

origin_resource = "zone"

[[link_resources]]
with = "subscription"
match_on = [ { property = "function", value = "public" } ]
create_relation = { type = "SATISFIES" }
copy_properties = [
  { from = "account", as = "record" }
]

[[link_resources]]
with = "subscription"
match_on = [ { property = "function", value = "private" } ]
create_relation = { type = "SATISFIES" }
copy_properties = [
  { from = "util", as = "record" }
]
